# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parish', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=20)),
                ('noOfPassengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DriverRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('APPROVED', 'approved'), ('DECLINED', 'declined')], default='DECLINED', max_length=8)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentLocation', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('noOfPeople', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('state', models.CharField(choices=[('UNDERWAY', 'underway'), ('ENDED', 'ended'), ('TOBEGIN', 'tobegin')], default='TOBEGIN', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carMake', models.CharField(max_length=50)),
                ('carModel', models.CharField(max_length=50)),
                ('carYear', models.CharField(max_length=4)),
                ('carColor', models.CharField(max_length=20)),
                ('licensePlate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='driver.Employee')),
                ('trn', models.IntegerField()),
                ('cellNum', models.CharField(max_length=10)),
                ('state', models.CharField(choices=[('AVAILABLE', 'available'), ('UNAVAILABLE', 'unavailable')], default='AVAILABLE', max_length=12)),
                ('currentJourney', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.Journey')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Vehicle')),
            ],
            bases=('driver.employee',),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Address'),
        ),
        migrations.AddField(
            model_name='driverrequest',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Journey'),
        ),
    ]
